version: "3.3"
   
services:
  web:
    build: .
    command: python manage.py test
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  test:
    build: .
  
    command: python manage.py test


